name: Build docker container and push to dockerhub
on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            TAG_NAME:
                description: 'Release Version Tag (0.0.0)'
                required: true
env:
  REGISTRY: ghcr.io
  CROSS_SYSROOT: /mnt/alpine

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Build container and push'
        permissions:
          packages: write
          contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1
              with:
                  ref: ${{ github.ref }}

            - name: Update Package to Release Version
              uses: technote-space/package-version-check-action@v1.9.3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Login to DockerHub
              uses: docker/login-action@v3.2.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push to GHCR Hub
              uses: docker/build-push-action@v6
              with:
                context: "."
                push: true
                tags: |
                    ghcr.io/sipcapture/expsuehep:latest
                    ghcr.io/sipcapture/expsuehep:${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
